name: "Unit tests"
run-name: ${{ github.actor }} is testing ethtool 🚀
on: [push, pull_request]
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - uses: ibiqlik/action-yamllint@v3
        with:
          format: auto

      - name: Run unit tests
        run: |
          go test -v -test.short ./...
